[workspace]
members = [".", "lf-hal", "lf-hal-types"]

[package]
edition = "2024"
name = "line_follower"
rust-version = "1.88"
version = "0.1.0"

[[bin]]
name = "line_follower"
path = "./src/bin/main.rs"
test = false

[[bin]]
name = "hal_test"
test = false

[[bin]]
name = "line_sensor_test"
test = false

[[bin]]
name = "calibrate_battery"
test = false

[[bin]]
name = "calibrate_distance"
test = false

[[bin]]
name = "velocity_control_test"
test = false

[dependencies]
deranged = { version = "0.5.8", default-features = false }
lf-hal-types = { path = "./lf-hal-types" }
embassy-time = { version = "0.5", features = ["tick-hz-1_000_000"] }
heapless = { version = "0.9" }

[target.'cfg(target_arch = "xtensa")'.dependencies]
lf-hal = { path = "./lf-hal" }
trouble-host = { version = "0.6", features = ["derive"] }
static_cell = { version = "2.1" }
embassy-futures = { version = "0.1" }
embassy-sync = { version = "0.7" }
esp-hal = { version = "~1.1", features = ["esp32", "log-04", "unstable"] }
esp-rtos = { version = "0.3.0", features = [
  "embassy",
  "esp-alloc",
  "esp-radio",
  "esp32",
  "log-04",
] }
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32", "log-04"] }
log = "0.4"
critical-section = "1.2.0"
embedded-io = "0.7.1"
esp-alloc = "0.10.0"
esp-backtrace = { version = "0.19.0", features = [
  "esp32",
  "panic-handler",
  "println",
] }
esp-println = { version = "0.17.0", features = ["esp32", "log-04"] }
embassy-executor = { version = "0.10.0", default-features = false }


[dev-dependencies]
proptest = "1"
test-strategy = "0.4.5"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
